#!/usr/bin/env bash
# ai-trend-report.sh — Daily AI trend content brief
# Runs at 7am via cron: 0 7 * * * /home/user/stack/scripts/ai-trend-report.sh
#
# What it does:
#   1. Searches for today's top AI trends via Brave Search MCP
#   2. Generates a ready-to-post LinkedIn content brief
#   3. Produces a primary post + A/B variant
#   4. Saves to logs/content-brief-YYYY-MM-DD.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
LOG_DIR="$ROOT/logs"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
REPORT="$LOG_DIR/content-brief-$DATE.md"

source "$ROOT/.env" 2>/dev/null || true
mkdir -p "$LOG_DIR"

echo "[$DATE $TIME] Generating AI trend report..." | tee -a "$LOG_DIR/session.log"

cat > "$REPORT" << EOF
# AI Trend Content Brief — $DATE

Generated: $TIME

---

EOF

claude --print --no-cache "
Today is $DATE. Use web search to find the top 3 most talked-about AI stories from the last 24-48 hours.

Focus on:
- New model releases or benchmarks
- AI tool launches or major updates
- Business/enterprise AI adoption news
- AI regulation or policy developments
- Surprising or contrarian AI takes getting traction

Then generate TWO LinkedIn posts following this exact format:

[PRIMARY POST]
<1-2 line hook that stops the scroll>

<Insight 1 — what's happening>

<Insight 2 — why it matters for professionals>

<Insight 3 — what to do about it>

<Takeaway + question CTA that invites comments>

---
Character count: XXX / 1300

[VARIANT POST]
<Different angle or hook on the same topic>

<3 insights with different framing>

<Different CTA>

---
Character count: XXX / 1300

Rules:
- Under 1300 characters each
- Line break every 2-3 sentences
- No corporate jargon
- Mobile-readable
- First person, direct voice
" >> "$REPORT" 2>&1 || echo "Note: Configure BRAVE_API_KEY in .env for web search access" >> "$REPORT"

cat >> "$REPORT" << EOF

---
*Report generated by ai-trend-report.sh at $TIME*
EOF

echo "[$DATE $TIME] Content brief saved to $REPORT" | tee -a "$LOG_DIR/session.log"

if command -v xdg-open &>/dev/null; then
  xdg-open "$REPORT" 2>/dev/null || true
fi
