#!/usr/bin/env bash
# daily-inbox.sh — LinkedIn inbox organiser
# Runs at 7am via cron: 0 7 * * * /home/user/stack/scripts/daily-inbox.sh
#
# What it does:
#   1. Fetches inbox via LinkedIn MCP
#   2. Categorises messages by priority
#   3. Drafts reply suggestions for Priority 1 items
#   4. Saves report to logs/inbox-YYYY-MM-DD.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
LOG_DIR="$ROOT/logs"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
REPORT="$LOG_DIR/inbox-$DATE.md"

source "$ROOT/.env" 2>/dev/null || true
mkdir -p "$LOG_DIR"

echo "[$DATE $TIME] Starting daily inbox organisation..." | tee -a "$LOG_DIR/session.log"

cat > "$REPORT" << EOF
# LinkedIn Inbox Report — $DATE

Generated: $TIME

---

## Priority 1 — Replies to Outreach (respond within 2 hours)

EOF

# Fetch inbox via Claude with LinkedIn MCP
claude --print --no-cache "
Use the linkedin_get_inbox tool to fetch the last 30 conversations.
Categorise each message into:
- Priority 1: Replies to my outreach messages (they replied to something I sent first)
- Priority 2: Connection requests with personalised notes
- Priority 3: General inbound messages
- Archive: Promotional, newsletter, or automated messages

For each Priority 1 message, draft a short reply suggestion (2-3 sentences) that:
- Acknowledges what they said specifically
- Moves the conversation forward
- Ends with one clear next step

Output in clean markdown with sections for each priority level.
" >> "$REPORT" 2>&1 || echo "Note: LinkedIn MCP connection required. Configure LINKEDIN_ACCESS_TOKEN in .env" >> "$REPORT"

cat >> "$REPORT" << EOF

---
*Report generated by daily-inbox.sh at $TIME*
EOF

echo "[$DATE $TIME] Inbox report saved to $REPORT" | tee -a "$LOG_DIR/session.log"

# Open report if on desktop
if command -v xdg-open &>/dev/null; then
  xdg-open "$REPORT" 2>/dev/null || true
fi
