#!/usr/bin/env bash
# team-report.sh — End-of-day consolidated team report
# Runs at 5pm via cron: 0 17 * * * /home/user/stack/scripts/team-report.sh
#
# What it does:
#   1. Scans the shared folder for files added today
#   2. Consolidates into a single team report
#   3. Posts summary to Slack channel (if configured)
#   4. Saves to logs/team-report-YYYY-MM-DD.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
LOG_DIR="$ROOT/logs"
SHARED_DIR="$ROOT/shared"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
REPORT="$LOG_DIR/team-report-$DATE.md"

source "$ROOT/.env" 2>/dev/null || true
mkdir -p "$LOG_DIR" "$SHARED_DIR"

echo "[$DATE $TIME] Generating end-of-day team report..." | tee -a "$LOG_DIR/session.log"

# Collect today's files from shared folder
TODAY_FILES=$(find "$SHARED_DIR" -type f -newer "$SHARED_DIR" -name "*.md" -o -name "*.txt" -o -name "*.json" 2>/dev/null | head -50)

cat > "$REPORT" << EOF
# Team Report — $DATE

Generated: $TIME

---

## Today's Activity Summary

EOF

if [ -z "$TODAY_FILES" ]; then
  echo "No new files added to shared folder today." >> "$REPORT"
else
  echo "Files processed today:" >> "$REPORT"
  echo "$TODAY_FILES" | while read -r file; do
    echo "- $(basename "$file")" >> "$REPORT"
  done
  echo "" >> "$REPORT"

  # Consolidate content via Claude
  CONTENT=""
  while IFS= read -r file; do
    if [ -f "$file" ]; then
      CONTENT="$CONTENT\n\n### $(basename "$file")\n$(cat "$file")"
    fi
  done <<< "$TODAY_FILES"

  echo "$CONTENT" | claude --print --no-cache "
You are consolidating an end-of-day team report. The following content was added to the shared folder today.

Summarise everything into a clean report with these sections:
1. Key Wins — what got done today
2. Outreach Activity — any LinkedIn messages sent, connections made, replies received
3. Content Created — posts written, content briefs generated
4. Leads Researched — any lead dossiers or enrichment done
5. Action Items for Tomorrow — what needs follow-up

Be concise. Use bullet points. This will be sent to the team via Slack.
" >> "$REPORT" 2>&1 || echo "Note: Configure Claude CLI to generate AI summaries" >> "$REPORT"
fi

# Post to Slack if configured
if [ -n "${SLACK_BOT_TOKEN:-}" ] && [ -n "${SLACK_REPORT_CHANNEL:-}" ]; then
  SUMMARY=$(head -50 "$REPORT" | tail -30)
  curl -s -X POST "https://slack.com/api/chat.postMessage" \
    -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
    -H "Content-Type: application/json" \
    -d "{
      \"channel\": \"$SLACK_REPORT_CHANNEL\",
      \"text\": \"*LinkedIn Team Report — $DATE*\n\`\`\`$(cat "$REPORT" | head -80)\`\`\`\"
    }" > /dev/null && echo "[$DATE $TIME] Report posted to Slack $SLACK_REPORT_CHANNEL" | tee -a "$LOG_DIR/session.log"
fi

cat >> "$REPORT" << EOF

---
*Report generated by team-report.sh at $TIME*
EOF

echo "[$DATE $TIME] Team report saved to $REPORT" | tee -a "$LOG_DIR/session.log"
